### ISSUE TITLE
wai-middleware-throttle-0.1.0.0 test suite failure

### ISSUE THREAD

**Issue by peti** [creichert/wai-middleware-throttle#1]
According to http://hydra.cryp.to/build/578727/nixlog/2/raw, the test suite tries to execute some external program that's not in $PATH. Unfortunately, the error message doesn't seem to reveal what that command is.

**Comment by creichert** [comment]
The test-suite runs `hlint`, `haddock`, and `doctest`. None of them are being heavily utilized (yet). Does that help locate which program it might be?

**Comment by peti** [comment]
Are those programs declared as `build-tools` for the test suite in the Cabal file? If any of those are undeclared, then our build sandbox won't contain the binary.

**Comment by creichert** [comment]
I just pushed a new release to Hackage which should address these issues. Is there somewhere I can subscribe to see these builds?

btw, `haddock` was the problematic exe and is the only one of the tools recognized by `build-tools`.

**Comment by peti** [comment]
Build tools that `Cabal` doesn't know about out-of-the-box should be registered in `Setup.hs` like so:

```
module Main ( main ) where

import Distribution.Simple
import Distribution.Simple.Program

main :: IO ()
main = defaultMainWithHooks simpleUserHooks
       { hookedPrograms = [ simpleProgram "zip" ]
       }
```

With that hook applied, `zip` becomes a valid build tool that can be used in the `Build-Tools` stanza.

**Comment by peti** [comment]
The test suite still fails in `wai-middleware-throttle-0.1.0.1`:

```
Running 3 test suites...
Test suite spec: RUNNING...
Test suite spec: PASS
Test suite logged to: dist/test/wai-middleware-throttle-0.1.0.1-spec.log
Test suite haddock: RUNNING...
haddock: cabal: readProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
Test suite haddock: FAIL
Test suite logged to: dist/test/wai-middleware-throttle-0.1.0.1-haddock.log
Test suite hlint: RUNNING...
Test suite hlint: PASS
Test suite logged to: dist/test/wai-middleware-throttle-0.1.0.1-hlint.log
2 of 3 test suites (2 of 3 test cases) passed.
```

It seems to me like your build depends on `cabal-install` in addition to `haddock`.

**Comment by creichert** [comment]
Just pushed a new version which should fix this:

https://hackage.haskell.org/package/wai-middleware-throttle-0.2.0.0
https://github.com/creichert/wai-middleware-throttle/blob/master/Setup.hs#L9

Thanks for keeping up on this, will be happy to fix any further issues.

**Comment by peti** [comment]
The test suite of 0.2.0.0 fails exactly the same way:

```
Running 3 test suites...
Test suite spec: RUNNING...
Test suite spec: PASS
Test suite logged to: dist/test/wai-middleware-throttle-0.2.0.0-spec.log
Test suite haddock: RUNNING...
haddock: cabal: readProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
Test suite haddock: FAIL
Test suite logged to: dist/test/wai-middleware-throttle-0.2.0.0-haddock.log
Test suite hlint: RUNNING...
Test suite hlint: PASS
Test suite logged to: dist/test/wai-middleware-throttle-0.2.0.0-hlint.log
2 of 3 test suites (2 of 3 test cases) passed.
```

The change in Setup.hs has no effect if no `build-tool:` dependency is declared in the Cabal file. Also, note that the package that provides `cabal` is called `cabal-install`. IMHO, you don't need the Setup.hs change at all to declare that dependency.

**Comment by peti** [comment]
Hmm, I just tried this locally, and it turns out that the name `cabal` must be used in the `build-tools:` stanza, even though the Haskell package that provides it is called `cabal-install`. It appears that `build-tools:` wants an executable name, really, not a package name.

**Comment by creichert** [comment]
I get the following error (I also get the same with `cabal-install`):

```
cabal: Uknown build tool cabal
```

I originally did not put it in the cabal file because I could not find it in the builtin programs: https://github.com/haskell/cabal/blob/ad6fe1cc39e4b01a50e57b836fea4ad1f5a1ad3d/Cabal/Distribution/Simple/Program/Builtin.hs#L13

I ended up putting it in the Setup.hs:
https://github.com/creichert/wai-middleware-throttle/blob/master/Setup.hs#L9

**Comment by peti** [comment]
Adding that snippet to `Setup.hs` has no effect on the build. All that code does is register `cabal` as a known build tool. With that code in place, you can now add `built-tools: cabal` to the Cabal file.

**Comment by peti** [comment]
Ping?

**Comment by creichert** [comment]
I just removed the Haddock tests for now and uploaded a new version: https://hackage.haskell.org/package/wai-middleware-throttle-0.2.0.1

Thanks for keeping up on this.

**Comment by creichert** [comment]
These issues should be fixed now (both test-suites have since been removed). Thanks again!
